// Automatically generated by PRGA's RTL generator
module lut4 (
    input wire [3:0] bits_in,
    output reg [0:0] out,

    input wire [0:0] cfg_clk,
    input wire [0:0] cfg_e,
    input wire [0:0] cfg_we,
    input wire [0:0] cfg_i,
    output wire [0:0] cfg_o
    );

    reg [15:0] cfg_d;
    reg [3:0] internal_in;
    
    // synopsys translate_off
    // in case the sensitivity list is never triggered
    initial begin
        internal_in = 6'b0;
        $dumpfile("dump.vcd");
        $dumpvars(1,lut4);
    end
    // synopsys translate_on

    always @* begin
        internal_in = bits_in;

        // synopsys translate_off
        // in simulation, force unconnected LUT input to be zeros
        if (bits_in[0] === 1'bx) begin
            internal_in[0] = 1'b0;
        end
        if (bits_in[1] === 1'bx) begin
            internal_in[1] = 1'b0;
        end
        if (bits_in[2] === 1'bx) begin
            internal_in[2] = 1'b0;
        end
        if (bits_in[3] === 1'bx) begin
            internal_in[3] = 1'b0;
        end
        // synopsys translate_on
    end

    always @* begin
        if (cfg_e) begin        // avoid pre-programming oscillating
            out = 1'b0;
        end else begin
            case (internal_in)  // synopsys infer_mux
                4'd0: out = cfg_d[0];
                4'd1: out = cfg_d[1];
                4'd2: out = cfg_d[2];
                4'd3: out = cfg_d[3];
                4'd4: out = cfg_d[4];
                4'd5: out = cfg_d[5];
                4'd6: out = cfg_d[6];
                4'd7: out = cfg_d[7];
                4'd8: out = cfg_d[8];
                4'd9: out = cfg_d[9];
                4'd10: out = cfg_d[10];
                4'd11: out = cfg_d[11];
                4'd12: out = cfg_d[12];
                4'd13: out = cfg_d[13];
                4'd14: out = cfg_d[14];
                4'd15: out = cfg_d[15];
            endcase
        end
    end

    wire [16:0] cfg_d_next;

    always @(posedge cfg_clk) begin
        if (cfg_e && cfg_we) begin
            cfg_d <= cfg_d_next;
        end
    end

    assign cfg_d_next = {cfg_d, cfg_i};
    assign cfg_o = cfg_d_next[16 -: 1];

endmodule