# -*- encoding: ascii -*-

"""Python source code generated by protoc."""

try:
    import common_pb2
    import bitchain_pb2
except ImportError as e:
    i = ("Failed to import 'comnon_pb2' and 'bitchain_pb2'. "
            "Maybe these two files are not generated yet. "
            "Please refer to the compile guide.")
    raise ImportError(i + '\n' + str(e))

__all__ = ['common_pb2', 'bitchain_pb2']
