// Automatically generated by PRGA's RTL generator
module {{ block.name }} (
    {%- set iocomma = joiner(",") %}
    {%- for port in block.ports %}{{ iocomma() }}
    {{ port.dir }} wire [{{ port.width - 1}}:0] {{ port.name }}
    {%- endfor %}
    );
    {% for wire in block.wires %}
    wire [{{ wire.width - 1}}:0] {{ wire.name }};
    {%- endfor %}
    {% for inst in block.instances %}
    {{ inst.model }} {{ inst.name }} (
        {%- set instcomma = joiner(",") %}
        {%- for pin in inst.pins %}{{ instcomma() }}
        .{{ pin.name }}({{ pin.connection }})
        {%- endfor %}
        );
    {%- endfor %}
    {% for assignment in block.assignments %}
    assign {{ assignment.to }} = {{ assignment.from }};
    {%- endfor %}
    
endmodule
