SIM = icarus
TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/../rtl/lut4.v
# TOPLEVEL is the name of the toplevel module in the Verilog or VHDL file_
TOPLEVEL=lut4
# MODULE is the name of the python testfile
MODULE=test

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim