SIM = icarus
TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/../rtl/{{module.name}}.v
# TOPLEVEL is the name of the toplevel module in the Verilog or VHDL file_
TOPLEVEL={{module.name}}
# MODULE is the name of the python testfile
MODULE={{module.test_name}}

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim