// Automatically generated by PRGA SimProj generator

`timescale 1ns/1ps
module {{ target.name }}_tb_top;

`ifdef FPGA_TEST
    localparam  bs_size = {{ config.bs_size }},
                bs_wordsize = {{ config.bs_wordsize }},
                bs_num_words = {{ config.bs_num_words }};
`endif

    // system control
    reg sys_clk, sys_rst;
    wire sys_success, sys_fail;

    // configuration (programming) control 
    localparam  INIT            = 3'd0,
                RESET           = 3'd1,
                PROGRAMMING     = 3'd2,
                PROG_DONE       = 3'd3,
                PROG_STABLIZING = 3'd4,
                TARGET_RUNNING  = 3'd5;

    reg [2:0] state;
`ifdef FPGA_TEST
    reg [0:256*8-1] bs_file;
    reg [bs_wordsize - 1:0] cfg_m [0:bs_num_words - 1];
`ifndef FAKE_PROG
    reg [2:0] state_next;
    reg cfg_e;
    wire cfg_clk = cfg_e & sys_clk;
    reg cfg_i;
    reg [63:0] cfg_progress;
    reg [7:0] cfg_percentage;
`endif
`endif

    // logging 
    reg tb_verbose;
    reg [0:256*8-1] dump_file;
    reg [31:0] cycle_count, max_cycle_count;

    // host wire
    wire host_rst = sys_rst || state != TARGET_RUNNING;

    // target wires
    {%- for name, width in iteritems(target.ports) %}
    wire {% if width %}[{{ width - 1 }}:0] {% endif %}guest_{{ name }};
    {%- endfor %}

    // test host
    {{ host.name }} {% if host.parameters %}#(
        {%- set comma4 = joiner(",") -%}
        {%- for k, v in iteritems(host.parameters) %}
        {{ comma4() }}.{{ k }}({{ v }})
        {%- endfor %}
    ) {% endif %}host (
        .sys_clk(sys_clk)
        ,.sys_rst(host_rst)
        ,.sys_success(sys_success)
        ,.sys_fail(sys_fail)
        ,.cycle_count(cycle_count)
        {%- for name in target.ports %}
        ,.{{ name }}(guest_{{ name }})
        {%- endfor %}
        );

    // test guest
`ifdef FPGA_TEST
    {{ guest.name }} guest (
`ifndef FAKE_PROG
        .cfg_clk(cfg_clk)
        ,.cfg_i(cfg_i)
        ,.cfg_e(cfg_e)
`else
        .cfg_clk()
        ,.cfg_i()
        ,.cfg_e(1'b0)
`endif
        {%- for port, connection in iteritems(guest.ports) %}
        ,.{{ port }}({% if connection %}guest_{{ connection }}{% endif %})
        {%- endfor %}
        );
`else
{%- if post_synthesis_sim %}
`ifdef POST_SYNTHESIS_SIM
    {{ target.name }} guest (
        {%- set comma = joiner(",") -%}
        {%- for name, width in iteritems(target.ports) %}
            {%- if width %}
                {%- for i in range(width) %}
        {{ comma() }}.{{ "\\" ~ name ~ "[" ~ i ~ "]" }} (guest_{{ name ~ "[" ~ i ~ "]" }})
            {%- endfor %}
            {%- else %}
        {{ comma() }}.{{ "\\" ~ name }} (guest_{{ name }})
            {%- endif %}
        {%- endfor %}
        );
`else
{%- endif %}
    {{ target.name }} {% if target.parameters %}#(
        {%- set comma5 = joiner(",") -%}
        {%- for k, v in iteritems(target.parameters) %}
        {{ comma5() }}.{{ k }}({{ v }})
        {%- endfor %}
    ) {% endif %}guest (
        {%- set comma3 = joiner(",") -%}
        {%- for name in target.ports %}
        {{ comma3() }}.{{ name }}(guest_{{ name }})
        {%- endfor %}
        );
{%- if post_synthesis_sim %}
`endif
{%- endif %}
`endif

    // test setup
    initial begin
        state = INIT;

        tb_verbose = 1'b1;
        if ($test$plusargs("testbench_silent")) begin
            tb_verbose = 1'b0;
        end

        if ($value$plusargs("dump_file=%s", dump_file)) begin
            if (tb_verbose)
                $display("[INFO] Dumping waveform: %s", dump_file);
            $dumpfile(dump_file);
            $dumpvars;
        end

        if (!$value$plusargs("max_cycle=%d", max_cycle_count)) begin
            max_cycle_count = 100_000;
        end

        if (tb_verbose)
            $display("[INFO] Max cycle count: %d", max_cycle_count);

`ifdef FPGA_TEST
        if (!$value$plusargs("bitstream_memh=%s", bs_file)) begin
            if (tb_verbose)
                $display("[INFO] Missing required argument: bitstream_memh");
            $finish;
        end

        $readmemh(bs_file, cfg_m);

`ifdef FAKE_PROG
        {%- for instance, base, length in guest.progs %}
            {%- for i in range(length) %}
                {%- set idx = config.bs_size - base - i - 1 %}
        guest.{{ instance }}.cfg_bit_{{ i }}.o = cfg_m[{{ idx // config.bs_wordsize }}][{{ idx % config.bs_wordsize }}];
            {%- endfor %}
        {%- endfor %}
`endif
`endif
        sys_clk = 1'b0;
        sys_rst = 1'b0;

        #{{ (clk_period|default(10)) * 0.25 }} sys_rst = 1'b1;

        #{{ (clk_period|default(10)) * 100 }} sys_rst = 1'b0;
    end

    // system clock generator
    always #{{ (clk_period|default(10)) / 2.0 }} sys_clk = ~sys_clk;

`ifdef FPGA_TEST
`ifndef FAKE_PROG
    // FSM
    always @(posedge sys_clk) begin
        if (sys_rst) begin
            state <= INIT;
        end else begin
            state <= state_next;
        end
    end

    // FSM next-stage logic
    always @* begin
        state_next = state;

        case (state)
            INIT: begin
                state_next = PROGRAMMING;
            end
            PROGRAMMING: begin
                if (cfg_progress == bs_size - 1) begin
                    state_next = PROG_DONE;
                end
            end
            PROG_DONE: begin
                state_next = PROG_STABLIZING;
            end
            PROG_STABLIZING: begin
                state_next = TARGET_RUNNING;
            end
        endcase
    end

    // FSM output
    always @* begin
        cfg_e = state == PROGRAMMING;
        cfg_i = cfg_m[cfg_progress / bs_wordsize][(cfg_progress % bs_wordsize)];
    end

    // configuration (programming) progress tracking
    always @(posedge sys_clk) begin
        if (state == PROGRAMMING) begin
            cfg_progress <= cfg_progress + 1;

            if (cfg_progress * 100 / bs_size >= cfg_percentage) begin
                if (tb_verbose)
                    $display("[INFO] [CONFIG] %3d%% config done (%d/%d)", cfg_percentage, cfg_progress, bs_size);
                cfg_percentage <= cfg_percentage + 1;
            end 
        end else begin
            cfg_progress <= 0;
            cfg_percentage <= 0;
        end
    end
`else
    always @(posedge sys_clk) begin
        if (sys_rst) begin
            state <= TARGET_RUNNING;
        end
    end
`endif
`else
    always @(posedge sys_clk) begin
        if (sys_rst) begin
            state <= TARGET_RUNNING;
        end
    end
`endif

    // cycle count tracking
    always @(posedge sys_clk) begin
        if (sys_rst) begin
            cycle_count <= 0;
        end else begin
            cycle_count <= cycle_count + 1;
        end

        if (~sys_rst && (cycle_count % 1_000 == 0)) begin
            if (tb_verbose)
                $display("[INFO] %3dK cycles passed", cycle_count / 1_000);
        end

        if (~sys_rst && (cycle_count >= max_cycle_count)) begin
            $display("[INFO] max cycle count reached, killing simulation");
            $finish;
        end
    end

    // test result reporting
    always @* begin
        if (~host_rst) begin
            if (sys_success) begin
                $display("[INFO] ********* all tests passed **********");
                $finish;
            end else if (sys_fail) begin
                $display("[INFO] ********* test failed **********");
                $finish;
            end
        end
    end

endmodule
