// Automatically generated by PRGA's RTL generator
module {{ module.name }} (
    {%- set portcomma = joiner(",") %}
    {%- for port in itervalues(module.physical_ports) %}{{ portcomma() }}
    {{ port.direction.name }} wire [{{ port.width - 1}}:0] {{ port.name }}
    {%- endfor %}
    );
    {% for instance in itervalues(module.physical_instances) %}
        {%- for pin in itervalues(instance.physical_pins) %}
            {%- if pin.is_output %}
    wire [{{ pin.width - 1 }}:0] {{ instance.name }}__{{ pin.name }};
            {%- endif %}
        {%- endfor %}
    {%- endfor %}
    {% for instance in itervalues(module.physical_instances) %}
    {{ instance.model.name }} {{ instance.name }} (
        {%- set pincomma = joiner(",") %}
        {%- for pin in itervalues(instance.physical_pins) %}{{ pincomma() }}
            {%- if pin.is_input %}
        .{{ pin.name }}({{ bits2verilog(pin.physical_source) }})
            {%- else %}
        .{{ pin.name }}({{ instance.name }}__{{ pin.name }})
            {%- endif %}
        {%- endfor %}
        );
    {%- endfor %}
    {% for port in itervalues(module.physical_ports) %}
        {%- if port.is_output %}
    assign {{ port.name }} = {{ bits2verilog(port.physical_source)|default("{}'bx".format(port.width), true) }};
        {%- endif %}
    {%- endfor %}

endmodule
