SIM = icarus
TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/ram.v
# TOPLEVEL is the name of the toplevel module in the Verilog or VHDL file_
TOPLEVEL=ram
# MODULE is the name of the python testfile
MODULE=ram_test

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim